recommendations = [
  # Default
  "streetsidesoftware.code-spell-checker",
  "usernamehw.errorlens",
  "eamodio.gitlens",
  "vscodevim.vim",
  "GitHub.vscode-github-actions",
  "GitHub.vscode-pull-request-github",

  # File format
  "bierner.markdown-mermaid",
  "hediet.vscode-drawio",

  # Remote
  "ms-vscode-remote.remote-containers",
  "ms-vscode-remote.remote-ssh",
  "ms-azuretools.vscode-docker",
  "oracle.mysql-shell-for-vs-code",

  # Programming Language
  "ArashSahebolamri.alloy",
  "DongyuZhao.alloy-vscode",
  "elmtooling.elm-ls-vscode",
  "jnoortheen.nix-ide",
  "HashiCorp.terraform",
  "ms-python.python",
  "scalameta.metals",
  "scala-lang.scala",

  # LLM
  "google.geminicodeassist",
  "github.copilot",
  "github.copilot-chat",
  "ms-vscode.vscode-speech",
  "ms-vscode.vscode-speech-language-pack-ja-jp",
]
