[env]
HOST = { script = ['if [[ $(uname) == "Darwin" ]]; then scutil --get ComputerName; else hostname; fi'] }

[tasks.apply]
mac_alias = "darwin:apply"

[tasks."H3JN70RHWY:apply"]
extend = "darwin:apply"
env = { HOST = "H3JN70RHWY" }

[tasks."Mac093:apply"]
extend = "darwin:apply"
env = { HOST = "Mac093" }

[tasks."darwin:apply"]
script = '''
nix build .#darwinConfigurations.${HOST}.system --extra-experimental-features 'nix-command flakes' --debug
sudo ./result/sw/bin/darwin-rebuild switch --flake ".#${HOST}"
'''
