name: "Nix Flake Syntax Check"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          connect-timeout = 60
          stalled-download-timeout = 90

    - name: Validate Nix flake syntax
      run: |
        nix flake show --json > /dev/null
        echo "✅ flake.nix syntax is valid!"

    - name: Check modules syntax
      run: |
        echo "Checking Nix syntax of module files..."
        find . -name "*.nix" -type f -print0 | xargs -0 -n1 nix-instantiate --parse > /dev/null || (echo "Syntax error found" && exit 1)
        echo "✅ All .nix files have valid syntax!"
