name: "Nix Flake Syntax Check"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  syntax-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main
      with:
        extra-conf: |
          connect-timeout = 60
          stalled-download-timeout = 90

    - name: Validate Nix flake syntax and show outputs
      run: |
        echo "=== Nix Flake Outputs ==="
        nix flake show
        echo "=== Detailed Flake Structure (JSON) ==="
        nix flake show --json
        echo "✅ flake.nix syntax is valid!"

    - name: Check modules syntax
      run: |
        echo "=== Checking Nix Module Files ==="
        echo "Finding all .nix files in the repository..."

        total_files=$(find . -name "*.nix" -type f | wc -l)
        echo "Found $total_files .nix files to check!"

        find . -name "*.nix" -type f | sort | while read -r file; do
          echo "Checking syntax: $file"
          if nix-instantiate --parse "$file" &> /dev/null; then
            echo "✓ $file - Syntax OK"
          else
            echo "❌ $file - Syntax Error!"
            exit 1
          fi
        done

        echo "✅ All .nix files have valid syntax!"
